// Turns an animation pack (sprite sheets drawn on a 24x24 pixel grid, one
// frame per 24 units along x, plain 1-unit <rect>s) into engine clips:
//
//   node tools/import-sheets.js "<pack>/sprites/cli"
//
// writes src/sprites-office.js. Re-run it whenever the pack changes; the
// output is generated, so edit the art, not that file.
//
// Why the frames stay at the art's own resolution: one art pixel is exactly
// 4 cells of the CLI skin's grid (head 12 px = 48 cells, arm nubs 2 px = 8,
// legs 1x2 px = ~5x8), so the clips carry `res: 0.25` and the engine draws
// each pixel as a 6-unit square. Art x=4 (the left arm nub) lands on the
// CLI grid's column 0, and the empty row under the feet (y=22) lands on the
// same ground headroom every other CLI frame has, so these clips stand
// exactly where his existing ones do.
'use strict';

const fs = require('fs');
const path = require('path');

const pack = process.argv[2];
if (!pack) {
  console.error('usage: node tools/import-sheets.js <pack>/sprites/cli');
  process.exit(1);
}
const manifest = JSON.parse(fs.readFileSync(path.join(pack, 'manifest.json'), 'utf8'));

// colour -> palette char. '#' and 'E' are the engine's body and eyes (so the
// talk squash and the chirp squint work on this art too); the body takes the
// CLI skin's own tone, so switching between old and new clips never flickers.
const CHARS = {
  '#D97757': '#', // body
  '#1A1A1C': 'E', // eyes
  '#D6CCBC': 'p', // paper, shade
  '#FBF8F1': 'P', // paper, light
  '#F3EEE4': 'q', // highlight
  '#8E877C': 'g', // ink lines
  '#C4913A': 'o', // gold, dark (watch)
  '#F2C66D': 'O', // gold, light
  '#9C6533': 'b', // box, dark
  '#C98B4E': 'B', // box
  '#EBD3AE': 't', // tape
  '#D8452C': 'r', // wax seal
};

const FRAME = 24;
const ART_X0 = 4;      // art column that lands on CLI grid column 0
const UNITS_PER_PX = 6; // 1.5 units per CLI cell x 4 cells per art pixel
const FEET_ROW = 22;   // first empty row under the feet

function readFrames(file, count) {
  const svg = fs.readFileSync(file, 'utf8').replace(/<metadata>[\s\S]*?<\/metadata>/, '');
  const frames = Array.from({ length: count }, () =>
    Array.from({ length: FRAME }, () => Array(FRAME).fill('.')));
  const re = /<rect x="(-?\d+)" y="(-?\d+)" width="(\d+)" height="(\d+)" fill="(#[0-9A-Fa-f]{6})"/g;
  let m;
  while ((m = re.exec(svg))) {
    const [x, y, w, h] = m.slice(1, 5).map(Number);
    const ch = CHARS[m[5].toUpperCase()];
    if (!ch) throw new Error(`${path.basename(file)}: unmapped colour ${m[5]}`);
    const f = Math.floor(x / FRAME);
    if (f < 0 || f >= count) continue;
    // later rects paint over earlier ones, as in the SVG
    for (let r = y; r < y + h; r++) {
      for (let c = x; c < x + w; c++) {
        const lc = c - f * FRAME;
        if (r >= 0 && r < FRAME && lc >= 0 && lc < FRAME) frames[f][r][lc] = ch;
      }
    }
  }
  return frames;
}

// the tightest box holding every frame of a clip, with the bottom kept at
// the ground line (or the frame's bottom edge, for art that rises from it)
function crop(allFrames, bottomRow) {
  let x0 = FRAME, x1 = -1, y0 = FRAME;
  for (const f of allFrames) {
    f.forEach((row, r) => row.forEach((ch, c) => {
      if (ch === '.') return;
      x0 = Math.min(x0, c); x1 = Math.max(x1, c); y0 = Math.min(y0, r);
    }));
  }
  return { x0, x1, y0, y1: bottomRow };
}

function cut(frame, b) {
  const out = [];
  for (let r = b.y0; r <= b.y1; r++) out.push((frame[r] || []).slice(b.x0, b.x1 + 1).join('').padEnd(b.x1 - b.x0 + 1, '.'));
  return out;
}

// engine name <- pack animation(s). `intro` plays once, `loop` repeats.
const CLIPS = {
  reading: { intro: 'letter-arrive', loop: 'letter-read' },
  clock: { loop: 'pocket-watch' },
  package: { loop: 'parcel' },
  happy_wiggle: { loop: 'happy-wiggle' },
  peek: { loop: 'peek', fromBottomEdge: true },
};

const out = [];
out.push('// GENERATED by tools/import-sheets.js from the Clawd character animation');
out.push('// series (CLI skin). Do not edit by hand: change the art and re-run it.');
out.push("'use strict';");
out.push('');
const names = [];
for (const [name, spec] of Object.entries(CLIPS)) {
  const parts = ['intro', 'loop'].filter((k) => spec[k]);
  const loaded = {};
  for (const k of parts) {
    const a = manifest.animations[spec[k]];
    if (!a) throw new Error(`manifest has no ${spec[k]}`);
    loaded[k] = { frames: readFrames(path.join(pack, a.sheet), a.frames), ms: Math.round(1000 / (a.fps || manifest.fps)) };
  }
  const box = crop(parts.flatMap((k) => loaded[k].frames), spec.fromBottomEdge ? FRAME - 1 : FEET_ROW);
  const dx = (box.x0 - ART_X0) * UNITS_PER_PX;
  // identical consecutive frames share one string table entry
  const table = [];
  const index = new Map();
  const ref = (f) => {
    const key = cut(f, box).join('\n');
    if (!index.has(key)) { index.set(key, table.length); table.push(cut(f, box)); }
    return index.get(key);
  };
  const steps = {};
  for (const k of parts) steps[k] = loaded[k].frames.map(ref);
  const id = name.toUpperCase();
  out.push(`const ${id}_F = ${JSON.stringify(table, null, 0).replace(/\],\[/g, '],\n  [')};`);
  const stage = (k) => (steps[k]
    ? `${id}_STEPS(${JSON.stringify(steps[k])}, ${loaded[k].ms})`
    : '[]');
  out.push(`const ${id}_STEPS = (ix, ms) => ix.map((i) => ({ frame: ${id}_F[i], dx: ${dx}, dy: 0, ms }));`);
  out.push(`const ${id} = { palette: 'office', motion: 'none', overlay: null, res: 0.25, stages: { intro: ${stage('intro')}, loop: ${stage('loop')}, outro: [] } };`);
  out.push('');
  names.push(`${name}: ${id}`);
}
out.push(`const OFFICE_CLI = { ${names.join(', ')} };`);
out.push('');
out.push('export { OFFICE_CLI };');
out.push('');

const dest = path.join(__dirname, '..', 'src', 'sprites-office.js');
fs.writeFileSync(dest, out.join('\n'));
console.log(`wrote ${path.relative(process.cwd(), dest)}: ${Object.keys(CLIPS).join(', ')}`);
