// Art styles: everything the engine needs to know about one buddy design.
// `app` is the Claude app mascot (the original pet), `cli` the Claude Code
// terminal mascot. Both stand on the same ground line at the same width, so
// panels, the "+" button and the hit region line up whichever is worn.
//
//   clips     the state -> clip table (sprites.js / sprites-cli.js)
//   spriteW/H base grid of the flat clips, in cells
//   cell      canvas units per base cell (app 8, cli 1.5 -> both 96 wide)
//   ground    canvas unit the sprite's bottom row sits on
//   snap      how cells hit device pixels: 'int' = one integer number of
//             device px per cell (the app's crisp 8-unit cells); 'edge' =
//             cell edges rounded to device px (the cli's 1.5-unit cells)
//   envelope  worst-case motion offsets around the rest rect, in units
//   anchors   overlay positions: dots/quest/rain relative to the frame origin
//             (ox, oy) or the sprite centre (cx); dream = the mini scene's
//             origin and units per frame cell inside the thought cloud
'use strict';

import { CLIPS, SPRITE_W, SPRITE_H } from './sprites.js';
import { CLIPS_CLI, CLI_W, CLI_H } from './sprites-cli.js';
import { OFFICE_CLI, OFFICE_APP } from './sprites-office.js';
import { EGG_CLI, EGG_APP } from './sprites-egg.js';
import { validateClips } from './sprite-kit.js';

// The assistant's new clips, and what each stands in with until it is drawn.
// The host only ever asks for the names on the left. Both skins' come from
// Nat's animation series (sprites-office.js, generated by
// tools/import-sheets.js); a clip missing from a pack falls back to the
// placeholder here, per skin.
//   reading       a message is being read out: holds up a tiny letter
//   clock         a meeting is due or late: taps a watch
//   package       a delivery arrived: carries a box in
//   happy_wiggle  clicked / petted
//   celebrate     the "waiting on you" list was just emptied
//   peek          idle variety: peeks in from the edge
//   hearts        love: your besties, and now and then when clicked
//   mad           a waiting item ignored through several nudges
//   talk          saying something longer (no mouth; a talking pose)
//   held          picked up: dangling and flailing (stand-in: his wave, swinging)
//   shake_off     back on his feet after a tumble, shaking it off
//   walk          strolling along the taskbar (drawn facing right; the host
//                 mirrors it for walking left)
// A placeholder is the clip it names, or { from, motion } to borrow a clip
// but move it differently.
const PLACEHOLDERS = {
  reading: 'thinking',
  clock: 'needs_input',
  package: 'done',
  happy_wiggle: 'wave',
  celebrate: 'wave',
  peek: 'idle',
  hearts: 'wave',
  mad: 'needs_input',
  talk: 'idle',
  walk: { from: 'idle', motion: 'walk' },
  held: { from: 'wave', motion: 'swing' },
  shake_off: { from: 'idle', motion: 'shake' },
};

function withPlaceholders(clips) {
  const out = { ...clips };
  for (const [name, stand] of Object.entries(PLACEHOLDERS)) {
    const from = typeof stand === 'string' ? stand : stand.from;
    const extra = typeof stand === 'string' ? {} : { motion: stand.motion };
    if (!out[name] && out[from]) out[name] = { ...out[from], ...extra, placeholderFor: from };
  }
  return out;
}

validateClips(OFFICE_CLI, CLI_W, CLI_H);
validateClips(OFFICE_APP, SPRITE_W, SPRITE_H);
// Walking left: the walk (drawn facing right) mirrored in the pixel data,
// so turning round is instant with no squash. Each frame is flipped about
// the body's centre line: a frame at offset dx and w units wide lands at
// (body width - dx - w).
function mirrored(clip, spriteW, cell) {
  if (!clip || !clip.stages) return clip;
  const flip = (s) => {
    const w = s.frame[0].length * (cell / (clip.res || 1));
    return { ...s, frame: s.frame.map((row) => [...row].reverse().join('')), dx: spriteW * cell - s.dx - w };
  };
  const st = clip.stages;
  return { ...clip, stages: { intro: st.intro.map(flip), loop: st.loop.map(flip), outro: st.outro.map(flip) } };
}

const CLI_ALL = { ...CLIPS_CLI, ...OFFICE_CLI, ...EGG_CLI };
const APP_ALL = { ...CLIPS, ...OFFICE_APP, ...EGG_APP };
if (OFFICE_CLI.walk) CLI_ALL.walk_left = mirrored(OFFICE_CLI.walk, CLI_W, 1.5);
if (OFFICE_APP.walk) APP_ALL.walk_left = mirrored(OFFICE_APP.walk, SPRITE_W, 8);

const UNIT_W = 160;

// Worst-case motion offsets measured over every frame of every clip: the
// frame art's extent at its step dx/dy against the rest rect, plus the
// engine motions (hop up 8, droop down 4, tilt/wobble/work +-2).
function measureEnvelope(clips, spriteW, spriteH, cell, ground) {
  const restW = spriteW * cell, restH = spriteH * cell;
  const restX = (UNIT_W - restW) / 2, restY = ground - restH;
  let left = 0, right = 0, up = 0, down = 0;
  for (const clip of Object.values(clips)) {
    const res = clip.res || 1, uc = cell / res;
    const steps = clip.frames ? clip.frames.map((f) => ({ frame: f, dx: 0, dy: 0 })) : [...clip.stages.intro, ...clip.stages.loop, ...clip.stages.outro];
    for (const s of steps) {
      const f = s.frame;
      let minC = Infinity, maxC = -1, minR = Infinity, maxR = -1;
      f.forEach((row, r) => {
        for (let c = 0; c < row.length; c++) if (row[c] !== '.') { minC = Math.min(minC, c); maxC = Math.max(maxC, c); minR = Math.min(minR, r); maxR = Math.max(maxR, r); }
      });
      if (maxC < 0) continue;
      const ox = restX + s.dx, oy = ground - f.length * uc + s.dy;
      left = Math.max(left, restX - (ox + minC * uc));
      right = Math.max(right, ox + (maxC + 1) * uc - (restX + restW));
      up = Math.max(up, restY - (oy + minR * uc));
      down = Math.max(down, oy + (maxR + 1) * uc - (restY + restH));
    }
  }
  return { left: Math.ceil(left) + 2, right: Math.ceil(right) + 2, up: Math.ceil(up) + 8, down: Math.ceil(down) + 4 };
}

const maxEnvelope = (a, b) => ({ left: Math.max(a.left, b.left), right: Math.max(a.right, b.right), up: Math.max(a.up, b.up), down: Math.max(a.down, b.down) });

const STYLES = {
  app: {
    name: 'app', clips: withPlaceholders(APP_ALL), spriteW: SPRITE_W, spriteH: SPRITE_H, cell: 8, ground: 148, snap: 'int',
    // the hand-measured envelope of the original clips, grown to fit the
    // animation series (confetti, the parcel overhead)
    envelope: maxEnvelope({ left: 28, right: 24, up: 48, down: 4 }, measureEnvelope(OFFICE_APP, SPRITE_W, SPRITE_H, 8, 148)),
    anchors: {
      dots: { x: 76, y: -12, step: 12 },
      quest: { x: -8, y: -28 },
      rain: { x: -14, y: -22 },
      dream: { x: 114, y: 76, cell: 1 },
    },
  },
  cli: {
    name: 'cli', clips: withPlaceholders(CLI_ALL), spriteW: CLI_W, spriteH: CLI_H, cell: 1.5, ground: 146, snap: 'edge',
    envelope: measureEnvelope(CLI_ALL, CLI_W, CLI_H, 1.5, 146),
    // the CLI head top sits 4 units lower in the frame than the app's (its
    // 8-unit headroom is 12 canvas units), so head-relative overlays drop 4
    anchors: {
      dots: { x: 76, y: -8, step: 12 },
      quest: { x: -8, y: -24 },
      rain: { x: -14, y: -18 },
      // 84-cell away frames at 0.4 units per cell = 34 units wide, inside
      // the cloud's 41-unit interior; step dx scales by 0.4/1.5
      dream: { x: 114, y: 76, cell: 0.4 },
    },
  },
};

export { STYLES, PLACEHOLDERS };
